// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfV57eZQulCh8fAyY5A3U4v1ndFTBof18',
    appId: '1:1043900447790:web:9ee5be3db879af1c7133bf',
    messagingSenderId: '1043900447790',
    projectId: 'kryspy-b0753',
    authDomain: 'kryspy-b0753.firebaseapp.com',
    storageBucket: 'kryspy-b0753.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUs6iypyZ6YuktrhGJJl_AKoq_kw25yf0',
    appId: '1:1043900447790:android:596e7b05e16b06767133bf',
    messagingSenderId: '1043900447790',
    projectId: 'kryspy-b0753',
    storageBucket: 'kryspy-b0753.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNgghoNvddMcOfOn_y43gGi5TXSiLGfw',
    appId: '1:1043900447790:ios:128f383ac2fa18be7133bf',
    messagingSenderId: '1043900447790',
    projectId: 'kryspy-b0753',
    storageBucket: 'kryspy-b0753.appspot.com',
    iosClientId: '1043900447790-1oacbm7qt9t8h5n9vvjlb6uegvm697qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kryspy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNgghoNvddMcOfOn_y43gGi5TXSiLGfw',
    appId: '1:1043900447790:ios:a97b07174e7f1f187133bf',
    messagingSenderId: '1043900447790',
    projectId: 'kryspy-b0753',
    storageBucket: 'kryspy-b0753.appspot.com',
    iosClientId: '1043900447790-4qkopm4sd1hfelj075imqlbmkot17vle.apps.googleusercontent.com',
    iosBundleId: 'com.example.kryspy.RunnerTests',
  );
}
